default:
  trainer: ppo

  beta: 1.0e-2
  epsilon: 0.2
  lambd: 0.95

  learning_rate: 3.0e-4
  learning_rate_schedule: linear

  max_steps: 1.0e8
  summary_freq: 50000

  normalize: false
  num_epoch: 3
  num_layers: 3
  hidden_units: 256
  
  use_recurrent: false
  sequence_length: 64
  memory_size: 128

  vis_encode_type: simple

  reward_signals:
    extrinsic:
      strength: 1.0
      gamma: 0.99

BikeContinuous:
  time_horizon: 256
  batch_size: 2048
  buffer_size: 20480

BikeDiscrete:
  time_horizon: 256
  batch_size: 128
  buffer_size: 2048


